"""initial migration with all tables

Revision ID: 222f5145d355
Revises: 
Create Date: 2026-05-10 16:07:56.057294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222f5145d355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto_imagenes_referencia', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_producto_imagenes_referencia_id'), 'producto_imagenes_referencia', ['id'], unique=False)
    op.drop_column('ventas', 'ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('ticket_id', sa.VARCHAR(length=20), nullable=True))
    op.drop_index(op.f('ix_producto_imagenes_referencia_id'), table_name='producto_imagenes_referencia')
    op.alter_column('producto_imagenes_referencia', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
